       ENVIRONMENT DIVISION.
       CONFIGURATION SECTION.
       SOURCE-COMPUTER. GnuCOBOL.
       SPECIAL-NAMES.
           CURSOR IS CURSOR-POSITION.
           CONSOLE IS CRT.
           CRT STATUS IS KEYBOARD-STATUS.
