#!/bin/bash
/usr/bin/which cobc >/dev/null 2>&1 || source $COBENV

PRG=$1
shift

DIR=$PWD
if [ -z "$COB_LIBRARY_PATH" ];
then
  export COB_LIBRARY_PATH=$DIR/LOADLIB:$DYLD_LIBRARY_PATH
fi
cobcrun -c $DIR/JCL/cob2_runtime.cfg $PRG $*
