#!/bin/bash
PRG=gcob
VERSION=251123
if [ $# -ne 1 ];
then
  echo "usage: gcob <member>"
  exit 1
fi
#
/usr/bin/which cobc >/dev/null 2>&1 || source $COBENV
#
BASENM=$1

source $TYCOBOL/JCL/tycobol.env


XOPT="-fdefault-colseq=EBCDIC -fdefaultbyte=0 -fdebugging-line"
OPT="-fno-gen-c-decl-static-call -fsingle-quote -ftsymbols -ftcmd -g -d"

cobc -I $CPY -ext cpy --save-temps=$SAVTMP $OPT -Wall -X -T $LST -o $OUT $INP

banner STOP
